{% set name = "nengo-spa" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3d1e9045880908d8129deb6484fed2606f18c25ce34fd5a1da6780f0d22e479d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - numpy
    - pip
    - python >=3.6
  run:
    - nengo >=2.7
    - numpy
    - python >=3.6

test:
  imports:
    - nengo_spa
    - nengo_spa.algebras
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.nengo.ai/nengo-spa/
  summary: An implementation of the Semantic Pointer Architecture for Nengo
  license: LicenseRef-NENGO
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - Tobias-Fischer
